### ISSUE TITLE
How to link this on Cmake?

### ISSUE THREAD

**Issue by Dekadencee** [r-lyeh/spot#11]
I tried to use spot on one of my proyects for convert .dds files to .jpg but I always get external simbols error on spot::color.

Any tip o idea to integrate this?

**Comment by r-lyeh** [comment]
Are you linking against `spot.cpp` and `spotc.c` files? 
You need `spot.hpp, spot.cpp and spotc.c` files only.
They're in the root project folder. Any other file is unneeded.

**Comment by Dekadencee** [comment]
I link spot as library, sorry my bad, now I link spot as simple files of my proyect:

`FILE(GLOB SpotFiles
	deps/spot/spot.hpp
	deps/spot/spot.c
	deps/spot/spot.cpp
)

add_executable(
	MyProyect
	${SpotFiles}
	${MainFiles}
)`

And on my code:

`#include "spot.hpp"

spot::image img = spot::image(dds.string().c_str());
img.save_as_jpg(out.c_str(), 100);`

But still showing linking errors(LNK2019) on my proyect :( on these functions:

- WebPGetInfo on "bool __cdecl spot::info(struct spot::stream &,void const *,unsigned __int64)"
- WebPDecodeRGBA on "bool __cdecl spot::decode(struct spot::stream &,struct spot::stream const &)"
- WebPEncodeRGBA on "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl spot::internals::encode_wbp(unsigned int,unsigned int,void const *,unsigned int)"

I don't know what its wrong now :/ my /deps/spot/ its a submodule of master of this repo.

**Comment by r-lyeh** [comment]
Don't rename spotc.c as spot.c. Try to keep the original name and tell me if it works :)
In your current setup spot.c will get converted into spot.o once compiled, but then spot.cpp as spot.o again (hence, overwriting the previous C file and missing all the whole file you previously compiled)

**Comment by Dekadencee** [comment]
Yes sorry, the fail its on "deps/spot/spot.c", i don't see that have a aditional "c" on his name, i renamed it to "deps/spot/spotc.c" and now the build it's fine ^^

A lot of thanks, I apreciate a lot your work, so usefull lightweight libraries for any proyect ^^

**Comment by r-lyeh** [comment]
De nada xD
