### ISSUE TITLE
support mac and linux

### ISSUE THREAD

**Issue by yingnierxiao** [r-lyeh/spot#7]

**Comment by r-lyeh** [comment]
it should compile both in mac and linux. got compiler errors? if so, please paste them in here

**Comment by yingnierxiao** [comment]
can you write makefile for converter to test

**Comment by r-lyeh** [comment]
I think `gcc -c spotc.c -I. -O2 && gcc -o converter samples/converter.cc spot.cpp spotc.o -I. -Isamples -std=c++11 -lX11 -lrt -pthread -O2` should be enough

**Comment by yingnierxiao** [comment]
gcc -c spotc.c -I. -O2 && g++ -o converter samples/converter.cc spot.cpp spotc.o -I. -Isamples -std=c++11 -lX11  -pthread -O2 -I/opt/X11/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/malloc -L/opt/X11/lib    it ok.   tks

**Comment by r-lyeh** [comment]
t2y :)
